### ISSUE TITLE
Error: Status Code: 420

### ISSUE THREAD

**Issue by replicants39715** [viswesh/Tweeties#1]
After receiving two tweets (one tweet and a duplicate of that tweet) or none at all, the following error appears:

```ruby
Error: Status Code: 420
Easy there, Turbo. Too many requests recently. Enhance your calm
```

Is there a way to delay the number of tweets being filtered out, for example: every 2 seconds, receive one tweet? Maybe i'm looking at it wrong, and there is another way around or i'm over seeing something?

I am new to node.js and would be grateful for any help.

**Comment by viswesh** [comment]
This is a common problem when using Twitter's free streaming service. Check out [Rate limiting](https://developer.twitter.com/en/docs/tweets/filter-realtime/guides/connecting.html) section. Whats interesting to me is that you received only 2 tweets and you get the error. That shoudnt happen. I recommend you wait and retry. 

Based on [twitter](https://www.npmjs.com/package/twitter) documentation, I dont see a way we can throttle incoming tweets. 

To take it further, I suggest that you enhance your error handling. When you get the error, disconnect the stream and reconnect after an interval. Hope that helps!

**Comment by replicants39715** [comment]
The twitter documentation doesn't really mention anything on throttling tweets as you mentioned but I stumbled on this module from the Snapkite Engine: [https://github.com/Snapkite/snapkite-stream-client](url).
Here, he seems to set a delay between tweets and gives us the option too cache or drop tweets.
I will try the tip you gave me with disconnecting the stream after an error/reconnecting after an interval, and in addition, take a deeper look in the Snapkite implementation. 

I would like to thank you for the quick and helpful response!

**Comment by viswesh** [comment]
Thanks! Let me know when you get the desired behavior.
