### ISSUE TITLE
Proxy error: Could not proxy request

### ISSUE THREAD

**Issue by StanislavBerezin** [viswesh/Tweeties#2]
I've cloned this repo and installed all of the required packages but it keeps giving me this error:

```
Proxy error: Could not proxy request /socket.io/?EIO=3&transport=polling&t=MPjIOZy from localhost:3000 to http://localhost:3001.
See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNREFUSED).

```

Is there a work around this? 

P.s i've tried changing ports etc but it didnt help

**Comment by viswesh** [comment]
The 'could not proxy request' error turns up if the node server at /src/server/server.js isn't running.

From your working directory: 
1. cd src/server
2. node server.js
3. <working directory> npm start

**Comment by viswesh** [comment]
Closing issue. Please let me know if you are still facing any roadblocks.
